//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SERVICEWEB.CINE.WS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pelicula
    {
        public System.Guid Id { get; set; }
        public string Titulo { get; set; }
        public string Genero { get; set; }
        public string Clasificacion { get; set; }
        public string Duracion { get; set; }
        public int AñoPublicacion { get; set; }
    }
}
